// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShowOnHomePage_Added_To_Product_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShowOnHomePage_Added_To_Product_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201903082032234_ShowOnHomePage_Added_To_Product_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
