// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product_AddColumn_Viewed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_AddColumn_Viewed));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241500254_Product_AddColumn_Viewed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
