// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Change_LastLoginDateProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Change_LastLoginDateProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201903281224219_User_Change_LastLoginDateProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
