// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Setting_Table_Creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setting_Table_Creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041816083_Setting_Table_Creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
