// <auto-generated />
namespace ECommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Slideshow_table_product_and_categories_short : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Slideshow_table_product_and_categories_short));
        
        string IMigrationMetadata.Id
        {
            get { return "201903131831325_Slideshow_table_product_and_categories_short"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
